#!/bin/sh

env=${1:-dev}

export UID
export GID=`id -g`
export COMPOSE_FILE="docker-compose.local.$env.yml"

if [ "$env" = "dev" ]; then
    docker-compose run --rm api npm install
fi

# Run initial setup
docker-compose run --rm api node lib/knex/sqlSecretsPrepare.js
docker-compose run --rm api npx knex migrate:latest --env dev_postgres
docker-compose run --rm api npx knex migrate:latest --env dev_st

docker-compose up -d
docker-compose run --rm api node lib/knex/sqlSecretsDestroy.js
